name: indexTestSimple
on: push
jobs:
  unit-test:
    name: testIndex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: test
        run: npm test
